spring.application.name=training-courses

spring.datasource.url=jdbc:postgresql://localhost:5433/db_training_courses
spring.datasource.username = user
spring.datasource.password=pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

logging.level.net.ttddyy.dsproxy.listener=debug
